#        _          _ ______ _____ _____
#       (_)        | |  ____|  __ \_   _|
#  _ __  ___  _____| | |__  | |  | || |
# | '_ \| \ \/ / _ \ |  __| | |  | || |
# | |_) | |>  <  __/ | |____| |__| || |_
# | .__/|_/_/\_\___|_|______|_____/_____|
# | |
# |_|
# https://links.pixeledi.eu
# ESPHome mqtt ping | 12.2024
#

substitutions:
 device_name: mqttping
 device_board: seeed_xiao_esp32c3
 device_type: arduino

packages:
  base: !include 00_common/main.yaml

interval:
  - interval: 5sec
    then:
      - mqtt.publish:
          topic: "studio/ping"
          payload: "ich bin im Raum"
